apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: javawebapp-ds
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: mushrifmulla/java-web-app:2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 9981
    nodePort: 31100
  