apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: test-ns
spec:
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app: javawebapp
  template:
    metadata:
      name: java-app-recreate
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp-recreate
        image: mushrifmulla/java-web-app:2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-recreate-deployment-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 9981
    nodePort: 30020

