apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-ns
  labels:
    app: nginx
spec:
  containers:
  - name: nginxapp
    image: nginx
    ports:
    - containerPort: 80
  - name: nodeapp
    image: mushrifmulla/node-app-mss:2
    ports:
    - containerPort: 9981
---
apiVersion: v1
kind: service
metadata:
  name: nginxsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010