apiVersion: v1
kind: ReplicationController
metadata:
  name: pythonrc
  namespace: test-ns
spec:
  replicas: 2
  selector:
    app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: mushrifmulla/python-flask-app:2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: service
metadata:
  name: pythonsvc
  namespace: test-ns
spec:
  type: NodePort
  selector: 
    app: pythonapp
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31000